### ISSUE TITLE
import problems

### ISSUE THREAD

**Issue by itelixgithub** [figengungor/country_pickers#4]
I've just encountered a problem when imporing the library:

`import 'package:country_code_picker/country_code_picker.dart';`

```
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  C:\IT_Projects\ISALON\isalon_app\lib\ScreenRegister.dart
...refers, in an import, to the following library:
  package:country_code_picker/country_code_picker.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?
```

heres my pubspec:
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: any
#  barcode_scan: ^1.0.0
#  qr_mobile_vision: ^0.2.2
  country_pickers: 1.0.0
```

the package appears as:
![lib](https://user-images.githubusercontent.com/38129401/54528505-75f15280-497d-11e9-8388-7ed4307d5832.JPG)

any ideas how to fix and use it properly ? Id like to use dropdown selector. Thanks
