### ISSUE TITLE
 Error: Method not found: 'ButtonTheme.bar'

### ISSUE THREAD

**Issue by Shiba-Kar** [figengungor/country_pickers#59]
```
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/country_pickers-1.3.0/lib/utils/my_alert_dialog.dart:139:36: Error: Method not found: 'ButtonTheme.bar'.
[   +1 ms] [        ]       children.add(new ButtonTheme.bar(
[        ] [        ]                                    ^^^

```
```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.844], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.53.2)
[√] Connected device (4 available)

```

**Comment by Shiba-Kar** [comment]
For temporary fix ``` .fromButtonThemeData ``` instead of  ``` .bar ```

**Comment by justkawal** [comment]
@Shiba-Kar 
It's also a temporary fix but It will be much easier.

In your pubspec.yaml remove the dependency of **country_pickers** and replace it with below dependency

```yaml
dependency_overrides:
  country_pickers:
    git:
      url: git://github.com/justkawal/country_pickers.git
      ref: master

```

~ Best
~ [justkawal](https://github.com/justkawal)
~ Long Live 🔥pen Source
